[General]
; set mif and msg language format type. 
; kr = korean
; jp = japanese
import_language = kr

; fix .x file error on read between magic number and header. might loss performance.
; if you have some model file exist but not visible in game, turn on this option.
; 0 = false
; 1 = true
fix_x_file_error = 1